elt_project:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      schema: co2_project
      threads: 4
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev
